// Centralized icon library configuration
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faHouse,
  faChartLine,
  faTrophy,
  faCrown,
  faFire,
  faStar,
  faHeart,
  faCheck,
  faXmark,
  faPlus,
  faMinus,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faCircleCheck,
  faCircleXmark,
  faCircleInfo,
  faCircleExclamation,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faBolt,
  faWandMagicSparkles,
  faMedal,
  faGem,
  faRocket,
  faBrain,
  faLeaf,
  faDumbbell,
  faBook,
  faUsers,
  faBullseye,
  faCalendar,
  faClock,
  faChartBar,
  faChartPie,
  faGear,
  faRightFromBracket,
  faEllipsisVertical,
  faBookOpen,
  faPenToSquare,
  faTrash,
  faArchive,
  faEye,
  faEyeSlash,
  faBell,
  faBellSlash,
  faEnvelope,
  faUser,
  faUserPlus,
  faLock,
  faUnlock,
  faMoon,
  faSun,
  faCircleUser,
  faArrowTrendUp,
  faArrowTrendDown,
  faCalendarDays,
  faClipboardCheck,
  faListCheck,
  faSquareCheck,
  faBars,
  faGripLines,
} from '@fortawesome/free-solid-svg-icons'

import {
  faCircle,
  faSquare,
  faStar as faStarRegular,
  faHeart as faHeartRegular,
  faCalendar as faCalendarRegular,
  faClock as faClockRegular,
  faUser as faUserRegular,
  faCircleCheck as faCircleCheckRegular,
} from '@fortawesome/free-regular-svg-icons'

// Add all icons to the library
library.add(
  // Solid icons
  faHouse,
  faChartLine,
  faTrophy,
  faCrown,
  faFire,
  faStar,
  faHeart,
  faCheck,
  faXmark,
  faPlus,
  faMinus,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faCircleCheck,
  faCircleXmark,
  faCircleInfo,
  faCircleExclamation,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faBolt,
  faWandMagicSparkles,
  faMedal,
  faGem,
  faRocket,
  faBrain,
  faLeaf,
  faDumbbell,
  faBook,
  faUsers,
  faBullseye,
  faCalendar,
  faClock,
  faChartBar,
  faChartPie,
  faGear,
  faRightFromBracket,
  faEllipsisVertical,
  faBookOpen,
  faPenToSquare,
  faTrash,
  faArchive,
  faEye,
  faEyeSlash,
  faBell,
  faBellSlash,
  faEnvelope,
  faUser,
  faUserPlus,
  faLock,
  faUnlock,
  faMoon,
  faSun,
  faCircleUser,
  faArrowTrendUp,
  faArrowTrendDown,
  faCalendarDays,
  faClipboardCheck,
  faListCheck,
  faSquareCheck,
  faBars,
  faGripLines,
  // Regular icons
  faCircle,
  faSquare,
  faStarRegular,
  faHeartRegular,
  faCalendarRegular,
  faClockRegular,
  faUserRegular,
  faCircleCheckRegular
)

// Export icon name mappings for easy use
export const Icons = {
  // Navigation
  home: faHouse,
  analytics: faChartLine,
  achievements: faTrophy,
  leaderboard: faCrown,
  templates: faBookOpen,
  
  // Gamification
  fire: faFire,
  star: faStar,
  trophy: faTrophy,
  medal: faMedal,
  gem: faGem,
  crown: faCrown,
  rocket: faRocket,
  sparkles: faWandMagicSparkles,
  
  // Actions
  check: faCheck,
  xmark: faXmark,
  plus: faPlus,
  minus: faMinus,
  edit: faPenToSquare,
  trash: faTrash,
  archive: faArchive,
  
  // Status
  circleCheck: faCircleCheck,
  circleXmark: faCircleXmark,
  circleInfo: faCircleInfo,
  circleExclamation: faCircleExclamation,
  
  // Arrows & Navigation
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  arrowUp: faArrowUp,
  arrowDown: faArrowDown,
  arrowTrendUp: faArrowTrendUp,
  arrowTrendDown: faArrowTrendDown,
  
  // Categories
  brain: faBrain,
  leaf: faLeaf,
  dumbbell: faDumbbell,
  book: faBook,
  users: faUsers,
  heart: faHeart,
  bolt: faBolt,
  target: faBullseye,
  
  // Time & Calendar
  calendar: faCalendar,
  calendarDays: faCalendarDays,
  clock: faClock,
  
  // Charts & Analytics
  chartBar: faChartBar,
  chartPie: faChartPie,
  chartLine: faChartLine,
  
  // User & Settings
  user: faUser,
  userPlus: faUserPlus,
  circleUser: faCircleUser,
  gear: faGear,
  signOut: faRightFromBracket,
  ellipsisVertical: faEllipsisVertical,
  
  // Visibility
  eye: faEye,
  eyeSlash: faEyeSlash,
  
  // Notifications
  bell: faBell,
  bellSlash: faBellSlash,
  envelope: faEnvelope,
  
  // Security
  lock: faLock,
  unlock: faUnlock,
  
  // Theme
  moon: faMoon,
  sun: faSun,
  
  // Lists & Tasks
  clipboardCheck: faClipboardCheck,
  listCheck: faListCheck,
  squareCheck: faSquareCheck,
  
  // Menu
  bars: faBars,
  gripLines: faGripLines,
} as const

export type IconName = keyof typeof Icons

